FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/conf.d/

# Create directory for the app
RUN mkdir -p /var/www/public

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]